#!/bin/python3
import subprocess


cur_theme = subprocess.check_output(["xfconf-query", "-c", "xsettings", "-p", "/Net/ThemeName"]).decode('utf-8')
if ("light" in cur_theme):
    subprocess.run(["sh","/usr/bin/set_night_mode"])
else:
    subprocess.run(["sh","/usr/bin/set_day_mode"])
